src/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from src.main.views import MainIndex, SignUp, ViewReport
from src.managers.views import Project, AddTeam, ProjectOptions
from src.users.views import AddReport, UserProfile
from src.main.views import Comment, Review, TimelyReports, EditReport
from src.main.views import TimeTracking
from src.notifications.views import Notification

urlpatterns = patterns('',
    # Examples:
    url(r'^$', MainIndex.as_view(), name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^maintainer/','src.main.views.maintainer', name='maintainer'),
    url(r'^maintenance', 'src.main.views.maintenance', name='maintenance'),
    url(r'^project', Project.as_view(), name='project'),
    url(r'^options', ProjectOptions.as_view(), name='project_options'),
    url(r'^add_team', AddTeam.as_view(), name='add_team'),
    url(r'^signup/$', SignUp.as_view(),
        name='signup_view'),

    url(r'^signin/$', 'django.contrib.auth.views.login',
        {'template_name': 'registration/login_form.html',
        'redirect_field_name' : '/' },
        name='signin'),

    url(r'^signout/$','django.contrib.auth.views.logout',
        {'next_page' : '/signin'}, name='signout'),
    url(r'^view_report', ViewReport.as_view(), name='view_report'),
    url(r'^report', AddReport.as_view(), name='report'),
    url(r'^access_denied', 'src.managers.views.access_denied'),
    url(r'^password_change', 'src.main.views.password_change'),
    url(r'^comment', Comment.as_view(), name='comment' ),
    url(r'^jsreverse/', 'src.main.views.jsreverse'),
    url(r'^day_wise_report', 'src.main.views.day_wise_reports', name='day_wise_report'),
    url(r'^review', Review.as_view(), name='review'),
    url(r'^notification', Notification.as_view(), name='notification'),
    url(r'^user_profile', UserProfile.as_view(), name='user_profile'),
    url(r'^timely_reports', TimelyReports.as_view(), name='timely_reports'),
    url(r'^edit_report', EditReport.as_view(), name='edit_report'),
    url(r'^time_tracking', TimeTracking.as_view(), name='time_tracking'),
    url(r'^members', 'src.main.views.members'),
    url(r'^delete_report', 'src.main.views.delete_report', name='delete_report'),
    url(r'^change_status', 'src.managers.views.change_status', name='change_status'),
    url(r'^view_history', 'src.managers.views.view_history', name='view_history'),
    url(r'^change_project_title', 'src.managers.views.change_project_title', name='change_project_title'),
    url(r'^restart_timer','src.main.views.restart_timer', name='restart_timer'),
)

src/main/models.py
#!/usr/bin/env python
#
# (c) 2015 CSIOM, http://www.csiom.com
#
# This file is part of DeeDee project.
#
# DeeDee is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# DeeDee is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with DeeDee.  If not, see <http://www.gnu.org/licenses/>.
#
#%% Authors %%
#Jasvir Singh Grewal <js@csiom.com>
#Aseem Mittal <aseemmittal@csiom.com>

"""
%% src/main/models.py %%
This file contains django model classes that will be used for ORM with database.. 
"""


from django.db import models
from django.contrib.auth.models import User
#from tinymce.models import HTMLField
import datetime
from src.users.models import DailyReport

class ReportComment(models.Model):
    """Model class for comments."""
    comment = models.TextField()
    report = models.ForeignKey(DailyReport)
    date = models.DateField(auto_now_add=True)
    time = models.TimeField(auto_now_add=True)
    commenter = models.ForeignKey(User)

class Rating(models.Model):
    """Model class for Rating"""
    rater = models.ForeignKey(User)
    rating = models.IntegerField()
    report = models.ForeignKey(DailyReport)
    comment = models.ForeignKey(ReportComment)

class Struggle(models.Model):
    """Model class for adding struggle type."""
    struggle_type = models.CharField(max_length=100)

    def __unicode__(self):
        return unicode(self.struggle_type)

class Reviewed(models.Model):
    """Model class for handeling review data."""
    report = models.ForeignKey(DailyReport)
    reviewer = models.ForeignKey(User)
    is_claimed = models.BooleanField(default=False)
    is_reviewed = models.BooleanField(default=False)
    date = models.DateField(auto_now_add=True)
    time=models.TimeField(auto_now_add=True)

class TimeTrackingData(models.Model):
    """Model class for holding temporary data required for time tracking"""
    start_time = models.DateTimeField()
    end_time = models.DateTimeField(null=True)
    user = models.ForeignKey(User)
    work_done = models.TextField(null=True)

class UserOfTimer(models.Model):
    """Model to track user of Time Tracker"""
    user = models.ForeignKey(User)
    datetime = models.DateTimeField(auto_now_add=True)

class PauseTimer(models.Model):
    """Model to store pause instances in timer."""
    start_time = models.DateTimeField()
    end_time = models.DateTimeField(null=True)
    currenlty_paused = models.BooleanField(default=True)
    user = models.ForeignKey(User)

src/main/forms.py
#!/usr/bin/env python
#
# (c) 2015 CSIOM, http://www.csiom.com
#
# This file is part of DeeDee project.
#
# DeeDee is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# DeeDee is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with DeeDee.  If not, see <http://www.gnu.org/licenses/>.
#
#%% Authors %%
#Jasvir Singh Grewal <js@csiom.com>
#Aseem Mittal <aseemmittal@csiom.com>

"""
%% src/main/forms.py %%
This file contains django form classes that can be used for data entry. 
"""

from django import forms
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from src.managers.models import ProjectDetails
from src.main.models import ReportComment, Rating
from django.utils.safestring import mark_safe
from django.forms.widgets import RadioSelect
import datetime


class RatingForm(forms.ModelForm):
    """Form for adding rating to reports."""
    class Meta:
      model = Rating
      exclude = ['rater','report','comment',]

class CommentForm(forms.ModelForm):
    """Form for addding comments."""
    class Meta:
      model = ReportComment
      exclude = ['report', 'commenter',]
      widgets = {
          'comment': forms.Textarea(attrs={'rows':4, 'cols':35}),
        }

class LoginForm(forms.Form):
    """Login Form"""
    username = forms.CharField(label="", max_length=20)
    password = forms.CharField(label ="", max_length=20,
                               widget=forms.PasswordInput)

class RegisterForm(forms.Form):
    """SignUp Form"""
    username = forms.CharField(label="username", max_length=20)
    password = forms.CharField(label ="password", max_length=20,
                               widget=forms.PasswordInput)
    password_confirmation = forms.CharField(label ="Confirm password",
                                            max_length=20,
                                            widget=forms.PasswordInput)
    email = forms.EmailField(max_length=50)


class ViewReportForm(forms.Form):
    """Form for viewing reports"""
    VIEW_CHOICES = (('','------'),('1', 'All'),('2', 'Teamwise'),)
    view = forms.ChoiceField(VIEW_CHOICES)
    project = forms.ModelChoiceField(queryset=ProjectDetails.objects.all())

    def __init__(self, manager, *args, **kwargs):
        super(ViewReportForm, self).__init__(*args, **kwargs)
        self.fields['project'] = forms.ModelChoiceField(
            queryset=ProjectDetails.objects.filter(manager=manager))
        self.fields['view'].widget.attrs={'class':'form-control'}
        self.fields['project'].widget.attrs={'class':'form-control'}

class DateSelectForm(forms.Form):
    """Form for selecting date."""
    date=forms.DateField(label="Select Date", required=False)
    name=forms.ModelChoiceField(queryset=User.objects.all(),required=False)

    def __init__(self, super_user_allow, manager_allow, normal_user_allow,
        superuser, *args, **kwargs):
        super(DateSelectForm, self).__init__(*args, **kwargs)
        if super_user_allow == 0 and not superuser:
            super_user_list = User.objects.values_list('id', flat=True).\
                filter(groups__name='super_user')
            if manager_allow == 1:
                self.fields['name'] = forms.ModelChoiceField(
                    queryset=User.objects.exclude(id__in=super_user_list).filter(),
                    required=False)
            else:
                manager_list = User.objects.values_list('id', flat=True).\
                filter(groups__name='managers')
                self.fields['name'] = forms.ModelChoiceField(
                    queryset=User.objects.exclude(id__in=super_user_list).\
                        exclude(id__in=manager_list).filter(),
                    required=False)
        self.fields['date'].widget.attrs={'id':'id_review_date'}
        self.fields['name'].widget.attrs={'class':'form-control'}


class HorizRadioRenderer(RadioSelect.renderer):
    """ this overrides widget method to put radio buttons horizontally
        instead of vertically.
    """
    def render(self):
            """Outputs radios"""
            return mark_safe(u'\n'.join([u'%s\n' % w for w in self]))


class DateRangeSelectionForm(forms.Form):
    """Form for selecting date range."""
    report_type = forms.ChoiceField()
    project = forms.ModelChoiceField(queryset=ProjectDetails.objects.all())
    members = forms.ModelChoiceField(queryset=User.objects.all().order_by('username'), required=False)
    start_date = forms.DateField()
    end_date = forms.DateField(initial=datetime.datetime.utcnow())

    def __init__(self, manager, super_user,*args, **kwargs):
        super(DateRangeSelectionForm, self).__init__(*args, **kwargs)
        if super_user == 1:
            self.fields['project'] = forms.ModelChoiceField(
                queryset=ProjectDetails.objects.all().order_by('title'), required=False)
            VIEW_CHOICES = (('1', 'Member/Project Reports'),('2', 'Complete Project Reports'),
                ('3', 'Memberwise'))
        else:
            self.fields['project'] = forms.ModelChoiceField(
                queryset=ProjectDetails.objects.filter(manager=manager).order_by('title'), required=False)
            VIEW_CHOICES = (('1', 'Member/Project Reports'),('2', 'Complete Project Reports'),)
        self.fields['report_type'] = forms.ChoiceField(VIEW_CHOICES,
            widget=forms.RadioSelect(renderer=HorizRadioRenderer))
        self.fields['project'].widget.attrs={'class':'form-control', 'id':'report-project'}
        self.fields['members'].widget.attrs={'id':'members-report','class':'form-control'}
        self.fields['start_date'].widget.attrs={'class':'form-control'}
        self.fields['end_date'].widget.attrs={'class':'form-control'}


class DateRangeForm(forms.Form):
    """Form for selecting date range."""

    start_date = forms.DateField()
    end_date = forms.DateField(initial=datetime.datetime.now())

    def __init__(self, *args, **kwargs):
        super(DateRangeForm, self).__init__(*args, **kwargs)

        self.fields['start_date'].widget.attrs={'class':'form-control'}
        self.fields['end_date'].widget.attrs={'class':'form-control'}

templates/main/daterangeselection.html
{% extends 'base.html' %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}
    <title>
        Timely Reports Form
    </title>
    {% endblock %}
    {% block extrajs %}
        <script src="{% static 'js/project_members.js' %}"></script>
    {% endblock %}
</head>
<body>
{% block content %}
<div class="container-fluid">

<div class='add_post'>
<form method='POST' action=''>
{% csrf_token %}
<table class="custom-form">
{% for field in form %}
    <div class="fieldWrapper">
    {% if not field.errors %}
    <tr>
        <th>{{ field.label_tag }}</th>
        <td>{{ field }}</td>
    </tr>
    {% else %}
    <tr>
        <th><font color="#a94442">{{ field.label_tag }}</font></label></th>
        <td class="has-error">{{ field }}</td>
    </tr>
    {% endif %}
    </div>
{% endfor %}
<tr>
	<td><br><span><input type="submit" name='report' id='report' class="btn btn-info btn-large btn-block" value="Report" ></td>
</tr>
</table>

</form>
</div>
</div>
{% endblock %}
</body>
</html>

templates/main/day_wise.html
{% extends 'base.html' %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}
    <title>
       Day wise Project Reports
    </title>
    {% endblock %}
    {% block extrajs %}
        <script src="{% static 'js/day_wise_reports.js' %}"></script>
    <script type="text/javascript">
    var reverseurl = "{% url 'src.main.views.jsreverse' %}";

        function reverse(urlstring, callback) {
            if (typeof callback != "function") {
                return false;
            }
            
            $.get(reverseurl + "?string=" + urlstring, callback);
        }
    </script>
    {% endblock %}
</head>
<body>
{% block content %}
<div class="container-fluid">
    <table class='custom-form'>
<tr>

        <td> <label> <b>Select Date:</b></label> <input id="id_review_date" name="date" type="text" /></td>
 
</tr>
</table>
<div id="day_wise_reports">

</div>
</div>
{% endblock %}
</body>
</html>

templates/main/list_drafts.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
	{% block title %}
	<title>
	Drafts	
	</title>
	{% endblock %}
</head>
<body>
{% block content %}
   {% for draft in draft_list %}
<h2>
  <a href="{{ draft.id }}">
    {{ draft.content }}
  </a>
</h2>
{% endfor %}
{% endblock %}
</body>
</html>

templates/main/list_post.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
	{% block title %}
	<title>
		List of Posts
	</title>
	{% endblock %}
</head>
<body>
{% block content %}
<table class='list_post'>
	<tr>
		<th>Title</th>
		<th>Options</th>
	</tr>
	{% for post in post %}
	<tr>
		<td>{{post.title}}</a></td>
		<td><a href="{% url 'post_list' %}?post={{post.id}}">Edit</a> | 
			<a href="{% url 'post_list' %}?post={{post.id}}&view=1">View</a></td>
	</tr>
	{% endfor %}
</table>
{% endblock %}
</body>
</html>

templates/main/list_report.html
<!DOCTYPE html>
<html lang="en">
<body>
<div class="container-fluid">
<table class="table table-hover table-striped">
    <tr>
        <th>Project</th>
        <th>Duration</th>
        <th>Date Time</th>
        <th>Options</th>
    </tr>
    {% for value in list %}
    <tr class="{{value.0}}">
        <td>{{value.1}}</td>
        <td>{{value.5}}</td>
        <td>{{value.2}} | {{value.3 | time:"H:i A"}}</td>
        <td><span id="report-options" ><a href="{% url 'view_report' %}/?report_id={{value.0}}&user_id={{value.4}}&report_info"><span class="glyphicon glyphicon-file" data-toggle="tooltip" data-placement="top" title="View Report"></span></a> </span> 
            | 
        <span id="report-options" ><a href="{% url 'edit_report' %}/?report_id={{value.0}}"><span class="glyphicon glyphicon-pencil" data-toggle="tooltip" data-placement="top" title="Edit Report"></span></a></span>
            |  
        <span class="delete-report" id="{{value.0}}"><i class="glyphicon glyphicon-trash" data-toggle="tooltip" data-placement="top" title="Delete Report" /></span></td>
    </tr>
    {% endfor %}
</table>
<h3>Total Time: {{total_hours}} Hours {{total_minutes}} Minutes</h3>
</body>
</html>

templates/main/post_added.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
	{% block title %}
	<title>
		Post Added
	</title>
	{% endblock %}
</head>
<body>
{% block content %}
<h3>Post Added/Saved Successfully</h3>
{% endblock %}
</body>
</html>

templates/main/report_search_result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>
        Report Options
    </title>
</head>
<body>
<table class="table table-hover table-striped ">
{% if view_val == 1 %}
{% for value in var_list %}
<tr>
    <td>{{value.user__username}}</td>
    <td>
    <a href = '{% url 'view_report' %}?list_report&user_id={{value.user__id}}&project_id={{value.project}}'>Report</a>
    </td>
</tr>
{% endfor %}
{% else %}
{% for value in var_list %}
<tr>
    <td>{{value.username}}</td>
    <td>
    <a href = '{% url 'view_report' %}?list_report&user_id={{value.id}}&project_id={{project_id}}'>Report</a>
    </td>
</tr>
{% endfor %}
{% endif %}
</table>
</body>
</html>

templates/main/report_summary.html
{% load i18n %} {% load staticfiles %}
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/summary.css' %}">
</head>
<body>
    <div class="container-fluid">
    <h4>Report written by
        {% if login_user != written_by_info.user %}
        {{written_by_info.user__username}}
        {% else %}
        you
        {% endif %}
        for {{written_by_info.project__project__title}} on {{written_by_info.date}}</h4>
        <table class="table table-hover table-striped">
            <tr>
                <th>Duration</th>
                <th>Work Done</th>
                <th>Struggle</th>
                <th>Tags</th>
            </tr>
            {% for value in list %}
            <tr>
                <td width="10%">{{value.duration_in_hours}}</td>
                <td width="35%">{{value.work_done | safe}}</td>
                <td width="35%">{{value.struggle}}</td>
                <td width="20%">{{value.tags}}</td>
            </tr>
            {% endfor %}
        </table>
    </div>
    </body>
    </html>

templates/main/review_select_result.html
<h3>Open For Review</h2>
<table class="table table-hover table-striped">
    <tr>
        <th>Reporter</th>
        <th>Project</th>
        <th>Date</th>
        <th>View Report</th>
        <th>Options</th>
    </tr>
    {% for value in open %}
    <tr>
        <td>{{value.user__username}}</td>
        <td>{{value.project__project__title}}</td>
        <td>{{value.date}}</td>
        <td><a href='report_id={{value.id}}&user_id={{value.user}}&report_summary' class='report_summary'>View Report</a></td>
        {% if value.reviewed__is_claimed %}
            <td>Claimed for review by {{value.reviewed__reviewer__username}}
                {% if value.reviewed__reviewer == user_id %}
                | <a href="{% url 'view_report' %}/?report_id={{value.id}}&user_id={{value.reviewed__reviewer}}&report_info">Review Now</td>
                {% else %}
            </td>
            {% endif %}
        {% else %}
            {% if value.user == user_id or value.project__project__manager == user_id %}
            <td>No one is reviewing this report.</td>
            {% else %}
            <td><a id="claim" href="{% url 'review' %}/?claim={{value.id}}">
                Claim for Review</a></td>
                {% endif %}
        {% endif %}
    </tr>
    {% endfor %}
</table>

templates/main/time_track.html
{% extends 'base.html' %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
        <meta charset="UTF-8">
		{% block title %}
        <title>Time Tracking</title>
		{% endblock %}
    {% block extrajs %}      
      <script src="{% static 'js/timer.js' %}"></script>
      <script type="text/javascript">
        $(document).ready(function(){
          $('#timer-status').hide();
          $('#timer-stoped').hide();
          $('#timer-paused').hide();
          $('.time_tracker_report_form').hide();
        });
      </script>
    {% endblock %}
</head>
<body>
{% block content %}
<div class="container-fluid">
  <div class="time_tracker_report_form">
    <form method='POST' >
      <div class="form-group">
        {% csrf_token %}
          <table class="custom-form">
            {% for field in reportform %}
              <div class="fieldWrapper">
                {% if forloop.first %}
                  <tr>
                      <td>{{field}}</td>
                  </tr>
                {% elif not field.errors %}
                  <tr>
                      <th>{{ field.label_tag }}</th>
                      <td>{{ field }}</td>
                  </tr>
                {% else %}
                  <tr>
                      <th><font color="#a94442">{{ field.label_tag }}</font></label></th>
                      <td class="has-error">{{ field }}</td>
                  </tr>
                {% endif %}
              </div>
            {% endfor %}
            {% for field in reportitem %}
              <div class="fieldWrapper">
                  {% if not field.errors %}
                  <tr>
                      <th>{{ field.label_tag }}</th>
                      <td>{{ field }}</td>
                  </tr>
                  {% else %}
                  <tr>
                      <th><font color="#a94442">{{ field.label_tag }}</font></label></th>
                      <td class="has-error">{{ field }}</td>
                  </tr>
                  {% endif %}
              </div>
            {% endfor %}
            </table>
           <br> 
            <table class="custom-form">
            <tr>
              <td><input class="btn btn-info btn-large btn-block" type='submit' value='Submit'></td>
              <td class='reset'><button type="button" class="btn btn-danger btn-large btn-block" id="reset-button"><span class="glyphicon glyphicon-time
glyphicon "></span><span class='button-label' id="reset-button-label">Reset Tracking</span></button></td>
</tr>
          </table>
        </div>
      </form>
    </div>
    {% if timer_stoped == 0 %}
       <div class ="timer"> 
       	<div id="time">
       		<p><span id="hours-value">{{time_string}}</span><span id="hours-label">Hours</span></p>
       	</div>
        {% if timer_status == 0 %}
		<button type="button" class="btn btn-success btn-large btn-block" id="timer-button"><span class="glyphicon glyphicon-off "></span><span class='button-label' id="button-label">Start Timer</span></button>
    <button type="button" class="btn btn-info btn-large btn-block" id="pause-button"><span id="pause-button-icon" class="glyphicon glyphicon-pause"></span><span class='button-label' id="pause-button-label">Pause Timer</span></button>
      {% else %}
      <button type="button" class="btn btn-danger btn-large btn-block" id="timer-button"><span class="glyphicon glyphicon-off "></span><span class='button-label' id="button-label">Stop Timer</span></button>
      {% if timer_paused == 0 %}
      <button type="button" class="btn btn-info btn-large btn-block" id="timer-button-pause"><span id="pause-button-icon" class="glyphicon glyphicon-pause"></span><span class='button-label' id="pause-button-label">Pause Timer</span></button>
      {% else %}
      <button type="button" class="btn btn-info btn-large btn-block" id="timer-button-pause"><span id="pause-button-icon" class="glyphicon glyphicon-play"></span><span class='button-label' id="pause-button-label">Resume Timer</span></button>
      {% endif %}
{% endif %}

	</div>
  {% endif %}
  <div class='hidden-values'>
  <p id="timer-status">{{timer_status}}</p>
          <p id="timer-stoped">{{timer_stoped}}</p>
          <p id="timer-paused">{{timer_paused}}</p>
        </div>
</div>
		{% endblock %}
</body>
</html>

templates/main/timely_report.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}
    <title>
        Reports
    </title>
    {% endblock %}
</head>
<body>
{% block content %}
<h4>Report 
{% if report_type != '3' %}
on {{project_name.title}}
{% endif %}
{% if report_type == '1' or report_type == '3' %}
for {{username.username}},
{% endif %}
from {{start_date}} to {{end_date}}</h4>
<div class="container-fluid">
<table class="table table-hover table-striped">
    <tr>
        <!-- <th id="long-th">Self Rating</th> -->
        {% if report_type == '2' %}
        <th>User</th>
        {% endif %}
        {% if report_type == '3' %}
        <th>Project</th>
        {% endif %}
        <th>Report Dated</th>
        <th>Duration(Hours)</th>
        <th>Work Done</th>
        <th>Struggle</th>
        <th>Self Rating</th>
        <th>Tags</th>
        <!-- <th>Rated</th> -->
    </tr>
    {% for value in var_list %}
    <tr>
        <!-- <td>{{value.self_rating}}</td> -->
        {% if report_type == '2' %}
        <td>{{value.daily_report__user__username}}</td>
        {% endif %}
        {% if report_type == '3' %}
        <td>{{value.daily_report__project__project__title}}</td>
        {% endif %}
        <td>{{value.daily_report__date}}</td>
        <td>{{value.duration_in_hours}}</td>
        <td>{{value.work_done}}</td>
        <td>{{value.struggle}}</td>
        <td>{{value.self_rating}}</td>
        <td>{{value.tags}}</td>
        <!-- <td>{{value.daily_report__rating__rating}}</td> -->
    </tr>
    {% endfor %}
</table>
{% if report_type == '1' or report_type == '3' %}
<h3>Total Time Dedicated: {{total_hours}} Hours {{total_minutes}} Minutes</h3>
{% else %}
<h3>Total Time: {{total_hours}} Hours {{total_minutes}} Minutes</h3>
{% endif %}
{% endblock %}
</body>
</html>

templates/main/view_post.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
	{% block title %}
	<title>
		List of Posts
	</title>
	{% endblock %}
</head>
<body>
{% block content %}
{% for value in post %}
<h3>{{value.title}}</h3>
{{value.content | safe}}
{% endfor %}
{% endblock %}
</body>
</html>

templates/main/view_report_options.html
{% extends 'base.html' %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}
    <title>
        Report Options
    </title>
    {% endblock %}
    {% block extrajs %}
        <script src="{% static 'js/view_option.js' %}"></script>
        <script src="{% static 'js/report_result.js' %}"></script>
    {% endblock %}
</head>
<body>
{% block content %}
<div class="container-fluid">
<div class='add_post'>
<form method='POST' action=''>

    <div class="form-group">
{% csrf_token %}
<table class='custom-form'>
<tr>
    <td><ul class="nav nav-pills">
  <li role="presentation" class="active"><a class="glyphicon glyphicon-retweet" href="{% url 'view_report' %}?list_report">&nbsp;My Reports</a></li>
  <li role="presentation" class="active"><a class="glyphicon glyphicon-time" href="{% url 'timely_reports' %}?list_report">&nbsp;Timely Reports</a></li>
</ul><br></td>
</tr>
<!--<tr>
{{ form.non_field_errors }}
<td>
    {{ form.view.errors }}
    <label for="id_view">View:</label>
    {{form.view }}
</td>
</tr>
<tr class="class_project">
<td>
    {{ form.project.errors }}
    <label for="id_project">Project:</label>
    {{ form.project }}
</td>
</tr>
-->
</table>
</div>
</form>
</div>
<div id='reportdatadiv'>
    
</div>
{% endblock %}
</body>
</html>