src/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from src.main.views import MainIndex, SignUp, ViewReport
from src.managers.views import Project, AddTeam, ProjectOptions
from src.users.views import AddReport, UserProfile
from src.main.views import Comment, Review, TimelyReports, EditReport
from src.main.views import TimeTracking
from src.notifications.views import Notification

urlpatterns = patterns('',
    # Examples:
    url(r'^$', MainIndex.as_view(), name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^maintainer/','src.main.views.maintainer', name='maintainer'),
    url(r'^maintenance', 'src.main.views.maintenance', name='maintenance'),
    url(r'^project', Project.as_view(), name='project'),
    url(r'^options', ProjectOptions.as_view(), name='project_options'),
    url(r'^add_team', AddTeam.as_view(), name='add_team'),
    url(r'^signup/$', SignUp.as_view(),
        name='signup_view'),

    url(r'^signin/$', 'django.contrib.auth.views.login',
        {'template_name': 'registration/login_form.html',
        'redirect_field_name' : '/' },
        name='signin'),

    url(r'^signout/$','django.contrib.auth.views.logout',
        {'next_page' : '/signin'}, name='signout'),
    url(r'^view_report', ViewReport.as_view(), name='view_report'),
    url(r'^report', AddReport.as_view(), name='report'),
    url(r'^access_denied', 'src.managers.views.access_denied'),
    url(r'^password_change', 'src.main.views.password_change'),
    url(r'^comment', Comment.as_view(), name='comment' ),
    url(r'^jsreverse/', 'src.main.views.jsreverse'),
    url(r'^day_wise_report', 'src.main.views.day_wise_reports', name='day_wise_report'),
    url(r'^review', Review.as_view(), name='review'),
    url(r'^notification', Notification.as_view(), name='notification'),
    url(r'^user_profile', UserProfile.as_view(), name='user_profile'),
    url(r'^timely_reports', TimelyReports.as_view(), name='timely_reports'),
    url(r'^edit_report', EditReport.as_view(), name='edit_report'),
    url(r'^time_tracking', TimeTracking.as_view(), name='time_tracking'),
    url(r'^members', 'src.main.views.members'),
    url(r'^delete_report', 'src.main.views.delete_report', name='delete_report'),
    url(r'^change_status', 'src.managers.views.change_status', name='change_status'),
    url(r'^view_history', 'src.managers.views.view_history', name='view_history'),
    url(r'^change_project_title', 'src.managers.views.change_project_title', name='change_project_title'),
    url(r'^restart_timer','src.main.views.restart_timer', name='restart_timer'),
)

src/users/models.py
#!/usr/bin/env python
#
# (c) 2015 CSIOM, http://www.csiom.com
#
# This file is part of DeeDee project.
#
# DeeDee is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# DeeDee is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with DeeDee.  If not, see <http://www.gnu.org/licenses/>.
#
#%% Authors %%
#Jasvir Singh Grewal <js@csiom.com>
#Aseem Mittal <aseemmittal@csiom.com>

"""
%% src/users/models.py %%
This file contains django model classes that will be used for ORM with database.
"""


from django.db import models
from django.contrib.auth.models import User

from src.managers.models import ProjectDetails
from src.managers.models import TeamMembers

import datetime

class DailyReport(models.Model):
    """Model class for adding report"""
    user = models.ForeignKey(User)
    project = models.ForeignKey(TeamMembers)
    date = models.DateField(auto_now_add=True)
    time = models.TimeField(auto_now_add=True)
    def __unicode__(self):
        return '%s' % (self.user) + ' on ' '%s' % (self.date)


class DailyReportItem(models.Model):
    """Models class for adding report item."""
    daily_report = models.ForeignKey(DailyReport)
    self_rating = models.IntegerField(default=100)
    duration_in_hours = models.CharField(max_length=5)
    work_done = models.TextField()
    struggle = models.TextField(default='Null')
    tags = models.TextField(blank=True)


class Gender(models.Model):
    """Model class for gender to use as foreign key in profile."""
    gender_type = models.CharField(max_length=100)
    def __unicode__(self):
        return '%s' % (self.gender_type)


class Profile(models.Model):
    """Model class for adding profile."""
    user = models.ForeignKey(User)
    first_name = models.CharField(max_length=500)
    last_name = models.CharField(max_length=500)
    gender = models.ForeignKey(Gender)
    skills = models.TextField(max_length=500)
    telephone = models.CharField(max_length=500)
    github = models.CharField(max_length=500)
    bitbucket = models.CharField(max_length=500)
    experience = models.TextField(max_length=500)

src/main/forms.py
#!/usr/bin/env python
#
# (c) 2015 CSIOM, http://www.csiom.com
#
# This file is part of DeeDee project.
#
# DeeDee is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# DeeDee is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with DeeDee.  If not, see <http://www.gnu.org/licenses/>.
#
#%% Authors %%
#Jasvir Singh Grewal <js@csiom.com>
#Aseem Mittal <aseemmittal@csiom.com>

"""
%% src/main/forms.py %%
This file contains django form classes that can be used for data entry. 
"""

from django import forms
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from src.managers.models import ProjectDetails
from src.main.models import ReportComment, Rating
from django.utils.safestring import mark_safe
from django.forms.widgets import RadioSelect
import datetime


class RatingForm(forms.ModelForm):
    """Form for adding rating to reports."""
    class Meta:
      model = Rating
      exclude = ['rater','report','comment',]

class CommentForm(forms.ModelForm):
    """Form for addding comments."""
    class Meta:
      model = ReportComment
      exclude = ['report', 'commenter',]
      widgets = {
          'comment': forms.Textarea(attrs={'rows':4, 'cols':35}),
        }

class LoginForm(forms.Form):
    """Login Form"""
    username = forms.CharField(label="", max_length=20)
    password = forms.CharField(label ="", max_length=20,
                               widget=forms.PasswordInput)

class RegisterForm(forms.Form):
    """SignUp Form"""
    username = forms.CharField(label="username", max_length=20)
    password = forms.CharField(label ="password", max_length=20,
                               widget=forms.PasswordInput)
    password_confirmation = forms.CharField(label ="Confirm password",
                                            max_length=20,
                                            widget=forms.PasswordInput)
    email = forms.EmailField(max_length=50)


class ViewReportForm(forms.Form):
    """Form for viewing reports"""
    VIEW_CHOICES = (('','------'),('1', 'All'),('2', 'Teamwise'),)
    view = forms.ChoiceField(VIEW_CHOICES)
    project = forms.ModelChoiceField(queryset=ProjectDetails.objects.all())

    def __init__(self, manager, *args, **kwargs):
        super(ViewReportForm, self).__init__(*args, **kwargs)
        self.fields['project'] = forms.ModelChoiceField(
            queryset=ProjectDetails.objects.filter(manager=manager))
        self.fields['view'].widget.attrs={'class':'form-control'}
        self.fields['project'].widget.attrs={'class':'form-control'}

class DateSelectForm(forms.Form):
    """Form for selecting date."""
    date=forms.DateField(label="Select Date", required=False)
    name=forms.ModelChoiceField(queryset=User.objects.all(),required=False)

    def __init__(self, super_user_allow, manager_allow, normal_user_allow,
        superuser, *args, **kwargs):
        super(DateSelectForm, self).__init__(*args, **kwargs)
        if super_user_allow == 0 and not superuser:
            super_user_list = User.objects.values_list('id', flat=True).\
                filter(groups__name='super_user')
            if manager_allow == 1:
                self.fields['name'] = forms.ModelChoiceField(
                    queryset=User.objects.exclude(id__in=super_user_list).filter(),
                    required=False)
            else:
                manager_list = User.objects.values_list('id', flat=True).\
                filter(groups__name='managers')
                self.fields['name'] = forms.ModelChoiceField(
                    queryset=User.objects.exclude(id__in=super_user_list).\
                        exclude(id__in=manager_list).filter(),
                    required=False)
        self.fields['date'].widget.attrs={'id':'id_review_date'}
        self.fields['name'].widget.attrs={'class':'form-control'}


class HorizRadioRenderer(RadioSelect.renderer):
    """ this overrides widget method to put radio buttons horizontally
        instead of vertically.
    """
    def render(self):
            """Outputs radios"""
            return mark_safe(u'\n'.join([u'%s\n' % w for w in self]))


class DateRangeSelectionForm(forms.Form):
    """Form for selecting date range."""
    report_type = forms.ChoiceField()
    project = forms.ModelChoiceField(queryset=ProjectDetails.objects.all())
    members = forms.ModelChoiceField(queryset=User.objects.all().order_by('username'), required=False)
    start_date = forms.DateField()
    end_date = forms.DateField(initial=datetime.datetime.utcnow())

    def __init__(self, manager, super_user,*args, **kwargs):
        super(DateRangeSelectionForm, self).__init__(*args, **kwargs)
        if super_user == 1:
            self.fields['project'] = forms.ModelChoiceField(
                queryset=ProjectDetails.objects.all().order_by('title'), required=False)
            VIEW_CHOICES = (('1', 'Member/Project Reports'),('2', 'Complete Project Reports'),
                ('3', 'Memberwise'))
        else:
            self.fields['project'] = forms.ModelChoiceField(
                queryset=ProjectDetails.objects.filter(manager=manager).order_by('title'), required=False)
            VIEW_CHOICES = (('1', 'Member/Project Reports'),('2', 'Complete Project Reports'),)
        self.fields['report_type'] = forms.ChoiceField(VIEW_CHOICES,
            widget=forms.RadioSelect(renderer=HorizRadioRenderer))
        self.fields['project'].widget.attrs={'class':'form-control', 'id':'report-project'}
        self.fields['members'].widget.attrs={'id':'members-report','class':'form-control'}
        self.fields['start_date'].widget.attrs={'class':'form-control'}
        self.fields['end_date'].widget.attrs={'class':'form-control'}


class DateRangeForm(forms.Form):
    """Form for selecting date range."""

    start_date = forms.DateField()
    end_date = forms.DateField(initial=datetime.datetime.now())

    def __init__(self, *args, **kwargs):
        super(DateRangeForm, self).__init__(*args, **kwargs)

        self.fields['start_date'].widget.attrs={'class':'form-control'}
        self.fields['end_date'].widget.attrs={'class':'form-control'}

templates/access_denied.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
	{% block title %}
	<title>
		Access Denied
	</title>
	{% endblock %}
</head>
<body>
{% block content %}
<h3>Access Denied</h3>
{% endblock %}
</body>
</html>

templates/base.html
{% load i18n %} 
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}
    {% endblock %}
    {% block extrahead %}
    <script type="text/javascript">
        var reverseurl = "{% url 'src.main.views.jsreverse' %}";

        function reverse(urlstring, callback) {
            if (typeof callback != "function") {
                return false;
            }
            
            $.get(reverseurl + "?string=" + urlstring, callback);
        }
    </script>
    {% endblock %}
    {% block js %}
        <script src="{% static 'js/jquery.min.js' %}">
    </script>
    <script src="{% static 'js/jquery-ui.min.js' %}">
    </script>
    <script src="{% static 'js/ie-emulation-modes-warning.js' %}"></script>
    <script src="{% static 'js/bootstrap-timepicker.min.js' %}">
    </script>
    <script src="{% static 'js/bootstrap-dialog.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
  <!--  <script src="{% static 'js/maintenance.js' %}"></script>-->

    {% block extrajs %}{% endblock %}
    {% endblock %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {% if access_var == 1 %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/manager_panel.css' %}">
    {% else %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/normal_user_panel.css' %}">
    {% endif %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-timepicker.min.css' %}">
    <script type="text/javascript">
    $(document).ready(function(){
      $('#id_published_date').datepicker({
            changeMonth: true,
            changeYear: true,dateFormat:"yy-mm-dd"
        })
        $('#id_published_date').datepicker( "option", "showAnim", "clip" )
        
      });
    </script>
    <script type="text/javascript">
    $(document).ready(function(){
      $('#id_start_date').datepicker({
            changeMonth: true,
            changeYear: true,dateFormat:"yy-mm-dd"
        })
        $('#id_start_date').datepicker( "option", "showAnim", "clip" )
        $('#id_end_date').datepicker({
            changeMonth: true,
            changeYear: true,dateFormat:"yy-mm-dd"
        })
        $('#id_end_date').datepicker( "option", "showAnim", "clip" )
      });
    </script>
    <script type="text/javascript">
    $(document).ready(function(){
      $('#id_date').datepicker({
            changeMonth: true,
            changeYear: true,dateFormat:"yy-mm-dd"
        })
        $('#id_date').datepicker( "option", "showAnim", "clip" )
      });
    </script>
    <script type="text/javascript">
    $(document).ready(function(){
      $('#id_review_date').datepicker({
            changeMonth: true,
            changeYear: true,dateFormat:"yy-mm-dd"
        })
        $('#id_review_date').datepicker( "option", "showAnim", "clip" )
      });
    </script>
    <script type="text/javascript">
    $(document).ready(function(){
    $('#id_duration_in_hours').timepicker({
            defaultTime: 'value',
            minuteStep: 1,
            disableFocus: true,
            template: 'dropdown',
            showMeridian:false
        });
    });
    </script>

    <link rel="stylesheet" type="text/css" href="{% static 'css/jquery-ui.css' %}">

</head>
<body>
    <div class = "wrapper">
    <div class="top-bar" id="top">
        <header id="header" class="header large-header">
            <div class="heading-container">
                <a id="heading" href="{% url 'home' %}"><h1 class="main-heading"><span class="head">CSIOM</span><span class='head'><img src="{% static 'icons/csiom.png' %}"></h1></a>
            </div>
            <nav class="primary-nav">
                <ul>

                {% for group in user.groups.all %}
                  {% if group.name == 'ceo' %}
                    <li><a href="{% url 'day_wise_report' %}"><button class="home">Track24</button></a></li>
                  {% endif %}
                {% endfor %}		

                <li><a href="{% url 'home' %}"><button class="home">Home</button></a></li>
                <li><a href="{% url 'time_tracking' %}"><button class="timer_option">Time Tracker</button>
                <li><a href="{% url 'report' %}/?add_report"><button class="add-report-link">Add Report</button></a></li>
                <li><a href='{% url 'src.main.views.password_change' %}'><button class="change-password">Change Password</button></a></li>
                <li><a href='{% url 'admin:logout' %}'><button class="log-out">Log Out</button></a></li>
                </ul>
            </nav>
        </header>
        </div>
    <div class="main-container">
               {% block content %}{% endblock %}
            </div>
    </div>  
</body>
</html>

templates/base_not_logged_in.html
{% load i18n %} {% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}
    {% endblock %}
    {% block extrahead %}
    <script type="text/javascript">
        var reverseurl = "{% url 'src.main.views.jsreverse' %}";

        function reverse(urlstring, callback) {
            if (typeof callback != "function") {
                return false;
            }
            
            $.get(reverseurl + "?string=" + urlstring, callback);
        }
    </script>
    {% endblock %}
    {% block js %}
        <script src="{% static 'js/jquery.min.js' %}">
    </script>
    <script src="{% static 'js/jquery-ui.min.js' %}">
    </script>
    <script src="{% static 'js/ie-emulation-modes-warning.js' %}"></script>
    <script src="{% static 'js/option_not_login.js' %}"></script>  
    <!--<script src="{% static 'js/maintenance.js' %}"></script>-->
 
    {% endblock %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>
<body>
    <div class = "wrapper">
    <div class="top-bar" id="top">
        <header id="header" class="header large-header">
            <div class="heading-container">
                <a id="heading" href="{% url 'home' %}"><h1 class="main-heading"><span class="head">CSIOM</span><span class='head'><img src="{% static 'icons/csiom.png' %}"></h1></a>
            </div>
            <nav class="primary-nav">
                <ul>
                    <div id="optional">
                
                    </div>
                </ul>
            </nav>
        </header>
        </div>
    <div class="main-container">
               {% block content %}{% endblock %}
            </div>
    </div>  
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
        <meta charset="UTF-8">
		{% block title %}
        <title>Index</title>
		{% endblock %}
</head>
<body>
       {% block content %}
       <div class ="main-box" id="c-panel"> 
		<ul class="panel-items">
		<li class="panel-item" id="profile">
			<a href="{% url 'user_profile' %}"><img src="{% static 'icons/User-Profile-256.png' %}"><span class="panel-text">Profile</span></a></li>
		{% if access_var == 1 %}
		<li class="panel-item" id "daily-reports">
			<a href="{% url 'project' %}"><img src="{% static 'icons/Project-256.png' %}"><span class="panel-text">Projects</span></a></li>
		{% endif %}
		{% if access_var == 1 %}
		<li class="panel-item" id "daily-reports">
			<a href="{% url 'add_team' %}"><img src="{% static 'icons/Group-Add-256.png' %}"><span class="panel-text">Team</span></a></li>
		{% endif %}
		<li class="panel-item" id "daily-reports">
			<a href="{% url 'view_report' %}"><img src="{% static 'icons/Report-Editor-256.png' %}"><span class="panel-text">Reports</span></a></li>
		<li class="panel-item" id "daily-reports">
			<a href="{% url 'review' %}"><img src="{% static 'icons/Double-Check-256.png' %}"><span class="panel-text">Review</span></a></li>
		<li class="panel-item" id "daily-reports">
			<a href="{% url 'notification' %}">
				{% if notice_status == 1 %}
				<img src="{% static 'icons/Notification-256-red.png' %}"><span class="panel-text">Notification</span></a></li>
            	{% else %}
          		<img src="{% static 'icons/Notification-256.png' %}"><span class="panel-text">Notification</span></a></li>	
          		 {% endif %}
		</ul>
	</div>
		{% endblock %}
</body>
</html>